# Generated by Django 4.0.2 on 2022-04-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=100, verbose_name='Documento')),
                ('permiso', models.CharField(max_length=100, verbose_name='Permiso')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('organizacion', models.CharField(max_length=100, verbose_name='Organizacion')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
