# Generated by Django 4.0.2 on 2022-04-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=100, verbose_name='Identificacion')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('numero_permiso', models.CharField(max_length=100, verbose_name='Numero de permiso')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('idVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSistema.visitante')),
            ],
        ),
    ]
