# Generated by Django 4.0.2 on 2022-04-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0002_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dirrecion_ip', models.CharField(max_length=100, verbose_name='Direccion IP')),
                ('dirrecion_mac', models.CharField(max_length=100, verbose_name='Direccion MAC')),
                ('identificador', models.CharField(max_length=100, verbose_name='Identificador')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Niveles_seguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(max_length=100, verbose_name='Tipo de acceso')),
            ],
        ),
        migrations.CreateModel(
            name='Punto_control',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Punto_control_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSistema.dispositivos')),
                ('idPunto_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSistema.punto_control')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('objetos', models.CharField(max_length=100, verbose_name='Objetos')),
                ('idNiveles_seguridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSistema.niveles_seguridad')),
            ],
        ),
    ]
