# Generated by Django 4.0.2 on 2022-04-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0003_dispositivos_niveles_seguridad_punto_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto_control_permiso',
            name='idDispositivos',
        ),
        migrations.AddField(
            model_name='punto_control_permiso',
            name='idPermiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSistema.permiso'),
        ),
        migrations.CreateModel(
            name='Punto_control_Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSistema.dispositivos')),
                ('idPunto_control_dispo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSistema.punto_control')),
            ],
        ),
    ]
