# Generated by Django 4.0.2 on 2022-04-28 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0004_remove_punto_control_permiso_iddispositivos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='idVisitante_permi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitante_permiso', to='mainSistema.visitante'),
        ),
    ]
