# Generated by Django 4.0.2 on 2022-05-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0005_permiso_idvisitante_permi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='idVisitante',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='numero_permiso',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='hora_ingreso',
            field=models.TimeField(null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='hora_salida',
            field=models.TimeField(null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='idPermiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSistema.permiso'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='idPtoCrontrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSistema.punto_control'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='autorizacion',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='punto_control',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='punto_control',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='permiso',
            field=models.CharField(max_length=50, verbose_name='permiso'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('idDispositivos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSistema.dispositivos')),
            ],
        ),
    ]
