# Generated by Django 4.0.2 on 2022-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0006_remove_ingreso_cargo_remove_ingreso_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles_seguridad',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
