# Generated by Django 4.0.2 on 2022-05-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0007_niveles_seguridad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='autorizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='permiso',
            field=models.BooleanField(default=False, max_length=50),
        ),
    ]
