# Generated by Django 4.0.2 on 2022-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0010_alter_permiso_idniveles_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='fecha_fin',
            field=models.TimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_inicio',
            field=models.TimeField(verbose_name='Fecha de inicio'),
        ),
    ]
