# Generated by Django 4.0.2 on 2022-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0011_alter_permiso_fecha_fin_alter_permiso_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
    ]
