# Generated by Django 4.0.2 on 2022-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0012_alter_permiso_fecha_fin_alter_permiso_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
