# Generated by Django 4.0.2 on 2022-05-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0015_rename_dirrecion_ip_dispositivos_direcion_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivos',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='punto_control',
            options={'verbose_name': 'Punto de Control', 'verbose_name_plural': 'Puntos de Control'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='idDispositivos',
            new_name='dispositivos_idDispositivos',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='observaciones',
            field=models.CharField(max_length=200, null=True, verbose_name='observaciones'),
        ),
    ]
