# Generated by Django 4.0.2 on 2022-05-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSistema', '0016_alter_dispositivos_options_alter_permiso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles_seguridad',
            name='idVisitante_nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idVisitante_nivel', to='mainSistema.visitante'),
        ),
    ]
